In [1]:
import pandas as pd

In [2]:
pwd

'C:\\Users\\pm453vw\\Documents\\Python Scripts'

In [7]:
df = pd.read_excel("TOTAL.xlsx", sheet_name=)

In [8]:
df

,Batch Name,Journal Name,Unnamed: 2,Unnamed: 3,LEDGER_ID,Transaction Number,JE Source Name,JE Category Name,Vendor Name,Line Number,...,SubAcct Description,Interco Description,Net Debit Local,Net Credit Local,Net Local,Net Debit Entered,Net Credit Entered,Net Entered,Net USD Budget,Journal Description
0,Revalues JAN-16 29-JAN-2016 622859,Revalues for USD income statement accounts,NaN,NaN,2328,NaN,Revaluation,Revalue Profit/Loss,NaN,2901,...,SubAccount Default,Default,1.62,0.00,1.62,0.00,0.00,0.00,0.0000,Revalues for USD income statement accounts
1,Revalues JAN-16 29-JAN-2016 622859,Revalues for USD income statement accounts,NaN,NaN,2328,NaN,Revaluation,Revalue Profit/Loss,NaN,1471,...,SubAccount Default,Default,0.67,0.00,0.67,0.00,0.00,0.00,0.0000,Revalues for USD income statement accounts
2,AT LOCAL: MMC DIVA A 511798 8170733 592431,JAN-16 MMC Pass Through EUR,NaN,NaN,2328,NaN,MMC DIVA,MMC Pass Through,NaN,3,...,SubAccount Default,Default,0.00,17.45,-17.45,0.00,17.45,-17.45,-18.6715,JAN-16 MMC Pass Through EUR
3,AT LOCAL: MMC DIVA A 511798 8170733 592431,JAN-16 MMC Pass Through EUR,NaN,NaN,2328,NaN,MMC DIVA,MMC Pass Through,NaN,3,...,SubAccount Default,Default,0.00,63.97,-63.97,0.00,63.97,-63.97,-68.4479,JAN-16 MMC Pass Through EUR
4,AT LOCAL: MMC DIVA A 511798 8170733 592431,JAN-16 MMC Pass Through EUR,NaN,NaN,2328,NaN,MMC DIVA,MMC Pass Through,NaN,3,...,SubAccount Default,Default,0.00,783.59,-783.59,0.00,783.59,-783.59,-838.4413,JAN-16 MMC Pass Through EUR
5,AT LOCAL: MMC DIVA A 511798 8170733 592431,JAN-16 MMC Pass Through EUR,NaN,NaN,2328,NaN,MMC DIVA,MMC Pass Through,NaN,3,...,SubAccount Default,Default,0.00,151.17,-151.17,0.00,151.17,-151.17,-161.7519,JAN-16 MMC Pass Through EUR
6,AT LOCAL: MMC DIVA A 511798 8170733 592431,JAN-16 MMC Pass Through EUR,NaN,NaN,2328,NaN,MMC DIVA,MMC Pass Through,NaN,3,...,SubAccount Default,Default,0.00,648.65,-648.65,0.00,648.65,-648.65,-694.0555,JAN-16 MMC Pass Through EUR
7,AT LOCAL: MMC DIVA A 511798 8170733 592431,JAN-16 MMC Pass Through EUR,NaN,NaN,2328,NaN,MMC DIVA,MMC Pass Through,NaN,3,...,SubAccount Default,Default,0.00,68.64,-68.64,0.00,68.64,-68.64,-73.4448,JAN-16 MMC Pass Through EUR
8,AT LOCAL: MMC DIVA A 511798 8170733 592431,JAN-16 MMC Pass Through EUR,NaN,NaN,2328,NaN,MMC DIVA,MMC Pass Through,NaN,3,...,SubAccount Default,Default,0.00,92.54,-92.54,0.00,92.54,-92.54,-99.0178,JAN-16 MMC Pass Through EUR
9,AT LOCAL: MMC DIVA A 533721 8199288 599348,JAN-16 MMC Pass Through EUR,NaN,NaN,2328,NaN,MMC DIVA,MMC Pass Through,NaN,6,...,SubAccount Default,Default,0.00,127.65,-127.65,0.00,127.65,-127.65,-136.5855,JAN-16 MMC Pass Through EUR
10,AT LOCAL: MMC DIVA A 533721 8199288 599348,JAN-16 MMC Pass Through EUR,NaN,NaN,2328,NaN,MMC DIVA,MMC Pass Through,NaN,6,...,SubAccount Default,Default,0.00,355.90,-355.90,0.00,355.90,-355.90,-380.8130,JAN-16 MMC Pass Through EUR
11,AT LOCAL: MMC DIVA A 533721 8199288 599348,JAN-16 MMC Pass Through EUR,NaN,NaN,2328,NaN,MMC DIVA,MMC Pass Through,NaN,6,...,SubAccount Default,Default,0.00,222.44,-222.44,0.00,222.44,-222.44,-238.0108,JAN-16 MMC Pass Through EUR
12,AT LOCAL: MMC DIVA A 533721 8199288 599348,JAN-16 MMC Pass Through EUR,NaN,NaN,2328,NaN,MMC DIVA,MMC Pass Through,NaN,6,...,SubAccount Default,Default,0.00,160.59,-160.59,0.00,160.59,-160.59,-171.8313,JAN-16 MMC Pass Through EUR
13,AT LOCAL: MMC DIVA A 533721 8199288 599348,JAN-16 MMC Pass Through EUR,NaN,NaN,2328,NaN,MMC DIVA,MMC Pass Through,NaN,6,...,SubAccount Default,Default,0.00,13681.31,-13681.31,0.00,13681.31,-13681.31,-14639.0017,JAN-16 MMC Pass Through EUR
14,AT LOCAL: MMC DIVA A 533721 8199288 599348,JAN-16 MMC Pass Through EUR,NaN,NaN,2328,NaN,MMC DIVA,MMC Pass Through,NaN,5,...,SubAccount Default,Default,2776.83,0.00,2776.83,2776.83,0.00,2776.83,2971.2081,JAN-16 MMC Pass Through EUR
15,AT LOCAL: MMC DIVA A 427724 7998317 517342,JAN-16 MMC Pass Through EUR,NaN,NaN,2328,NaN,MMC DIVA,MMC Pass Through,NaN,4,...,SubAccount Default,Default,0.00,1798.38,-1798.38,0.00,1798.38,-1798.38,-1924.2666,JAN-16 MMC Pass Through EUR
16,AT LOCAL: MMC DIVA A 338449 7579511 462054,JAN-16 MMC Pass Through USD,NaN,NaN,2328,NaN,MMC DIVA,MMC Pass Through,NaN,2,...,SubAccount Default,Default,0.00,3319.36,-3319.36,0.00,3563.00,-3563.00,-3563.0000,JAN-16 MMC Pass Through USD
17,AT LOCAL: MMC DIVA A 338449 7579511 462054,JAN-16 MMC Pass Through USD,NaN,NaN,2328,NaN,MMC DIVA,MMC Pass Through,NaN,1,...,SubAccount Default,Default,0.00,8400.22,-8400.22,0.00,9016.80,-9016.80,-9016.8000,JAN-16 MMC Pass Through USD
18,AT LOCAL: MMC DIVA A 471717 8059521 555335,JAN-16 MMC Pass Through EUR,NaN,NaN,2328,NaN,MMC DIVA,MMC Pass Through,NaN,6,...,SubAccount Default,Default,0.00,7030.00,-7030.00,0.00,7030.00,-7030.00,-7522.1000,JAN-16 MMC Pass Through EUR
19,AT LOCAL: MMC DIVA A 471717 8059521 555335,JAN-16 MMC Pass Through EUR,NaN,NaN,2328,NaN,MMC DIVA,MMC Pass Through,NaN,6,...,SubAccount Default,Default,0.00,50.20,-50.20,0.00,50.20,-50.20,-53.7140,JAN-16 MMC Pass Through EUR
20,AT LOCAL: MMC DIVA A 379073 7907039 495141,FEB-16 MMC Pass Through EUR,NaN,NaN,2328,NaN,MMC DIVA,MMC Pass Through,NaN,2,...,SubAccount Default,Default,0.00,1824.00,-1824.00,0.00,1824.00,-1824.00,-1951.6800,FEB-16 MMC Pass Through EUR
21,AT LOCAL: MMC DIVA A 379073 7907039 495141,FEB-16 MMC Pass Through EUR,NaN,NaN,2328,NaN,MMC DIVA,MMC Pass Through,NaN,2,...,SubAccount Default,Default,0.00,859.95,-859.95,0.00,859.95,-859.95,-920.1465,FEB-16 MMC Pass Through EUR
22,AT LOCAL: MMC DIVA A 379073 7907039 495141,FEB-16 MMC Pass Through EUR,NaN,NaN,2328,NaN,MMC DIVA,MMC Pass Through,NaN,2,...,SubAccount Default,Default,0.00,6963.52,-6963.52,0.00,6963.52,-6963.52,-7450.9664,FEB-16 MMC Pass Through EUR
23,AT LOCAL: MMC DIVA A 379073 7907039 495141,FEB-16 MMC Pass Through EUR,NaN,NaN,2328,NaN,MMC DIVA,MMC Pass Through,NaN,2,...,SubAccount Default,Default,0.00,305.97,-305.97,0.00,305.97,-305.97,-327.3879,FEB-16 MMC Pass Through EUR
24,AT LOCAL: MMC DIVA A 379073 7907039 495141,FEB-16 MMC Pass Through EUR,NaN,NaN,2328,NaN,MMC DIVA,MMC Pass Through,NaN,2,...,SubAccount Default,Default,0.00,1313.82,-1313.82,0.00,1313.82,-1313.82,-1405.7874,FEB-16 MMC Pass Through EUR
25,AT LOCAL: MMC DIVA A 379073 7907039 495141,FEB-16 MMC Pass Through EUR,NaN,NaN,2328,NaN,MMC DIVA,MMC Pass Through,NaN,2,...,SubAccount Default,Default,0.00,2555.77,-2555.77,0.00,2555.77,-2555.77,-2734.6739,FEB-16 MMC Pass Through EUR
26,AT LOCAL: MMC FAH WEBADI REV SVM A 458875 8044...,92503-AT-T3-VSA-1215-AB-DIVA Interface 21-23 D...,NaN,NaN,2328,NaN,MMC FAH WEBADI REV SVM,FAH Accrual,NaN,80,...,SubAccount Default,Default,16500.00,0.00,16500.00,16500.00,0.00,16500.00,17655.0000,DIVA Interface 21-23 Dec 15 - URGENT EUR
27,AT LOCAL: MMC FAH WEBADI REV SVM A 458875 8044...,84674-AT-T3-AST-1215-AB-DIVA 3297 - 23RD NOV 1...,NaN,NaN,2328,NaN,MMC FAH WEBADI REV SVM,FAH Accrual,NaN,6,...,SubAccount Default,Default,2991.43,0.00,2991.43,3211.00,0.00,3211.00,3211.0000,DIVA 3297 - 23RD NOV 15 JOURNAL USD
28,AT LOCAL: MMC FAH ADI A 561809 8262145 608386,AT-T3-SGC-0116-JK- Accruals over 90 days - 01/...,NaN,NaN,2328,NaN,MMC FAH ADI,FAH Accrual,NaN,1,...,SubAccount Default,Default,44000.00,0.00,44000.00,44000.00,0.00,44000.00,47080.0000,January Accruals over 90 days EUR
29,AT LOCAL: MMC FAH ADI A 566641 8300960 615094,102725-MAR-AT-T4-PB-0116-Austria Global Alloca...,NaN,NaN,2328,NaN,MMC FAH ADI,FAH Accrual,NaN,72,...,SubAccount Default,Default,0.00,6098.50,-6098.50,0.00,6631.51,-6631.51,-6631.5100,Austria Global Allocation- Jan-16 USD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48124,AT LOCAL: MMC DIVA A 2674990 16055904 2669872,DEC-16 MMC Pass Through EUR,NaN,NaN,2328,NaN,MMC DIVA,MMC Pass Through,NaN,25,...,SubAccount Default,Default,0.00,8.31,-8.31,0.00,8.31,-8.31,-8.8917,DEC-16 MMC Pass Through EUR
48125,AT LOCAL: MMC DIVA A 2674990 16055904 2669872,DEC-16 MMC Pass Through EUR,NaN,NaN,2328,NaN,MMC DIVA,MMC Pass Through,NaN,25,...,SubAccount Default,Default,0.00,14.37,-14.37,0.00,14.37,-14.37,-15.3759,DEC-16 MMC Pass Through EUR
48126,AT LOCAL: MMC DIVA A 2674990 16055904 2669872,DEC-16 MMC Pass Through EUR,NaN,NaN,2328,NaN,MMC DIVA,MMC Pass Through,NaN,25,...,SubAccount Default,Default,0.00,8.88,-8.88,0.00,8.88,-8.88,-9.5016,DEC-16 MMC Pass Through EUR
48127,AT LOCAL: MMC DIVA A 2674990 16055904 2669872,DEC-16 MMC Pass Through EUR,NaN,NaN,2328,NaN,MMC DIVA,MMC Pass Through,NaN,25,...,SubAccount Default,Default,0.00,10.07,-10.07,0.00,10.07,-10.07,-10.7749,DEC-16 MMC Pass Through EUR
48128,AT LOCAL: MMC DIVA A 2674990 16055904 2669872,DEC-16 MMC Pass Through EUR,NaN,NaN,2328,NaN,MMC DIVA,MMC Pass Through,NaN,25,...,SubAccount Default,Default,0.00,10.07,-10.07,0.00,10.07,-10.07,-10.7749,DEC-16 MMC Pass Through EUR
48129,AT LOCAL: MMC DIVA A 2674990 16055904 2669872,DEC-16 MMC Pass Through EUR,NaN,NaN,2328,NaN,MMC DIVA,MMC Pass Through,NaN,25,...,SubAccount Default,Default,0.00,10.07,-10.07,0.00,10.07,-10.07,-10.7749,DEC-16 MMC Pass Through EUR
48130,AT LOCAL: Receivables A 2711381 16812393 2713166,DEC-16 Receipts EUR,NaN,NaN,2328,NaN,Receivables,Receipts,NaN,1,...,SubAccount Default,Default,4625.77,0.00,4625.77,4625.77,0.00,4625.77,4949.5739,DEC-16 Receipts EUR
48131,Revalues DEC-16 29-DEC-2016 2721715,Revalues for USD income statement accounts,NaN,NaN,2328,NaN,Revaluation,Revalue Profit/Loss,NaN,31,...,SubAccount Default,Default,65.30,0.00,65.30,0.00,0.00,0.00,0.0000,Revalues for USD income statement accounts
48132,Revalues DEC-16 29-DEC-2016 2721715,Revalues for USD income statement accounts,NaN,NaN,2328,NaN,Revaluation,Revalue Profit/Loss,NaN,661,...,SubAccount Default,Default,312.58,0.00,312.58,0.00,0.00,0.00,0.0000,Revalues for USD income statement accounts
48133,Revalues DEC-16 29-DEC-2016 2721715,Revalues for USD income statement accounts,NaN,NaN,2328,NaN,Revaluation,Revalue Profit/Loss,NaN,1551,...,SubAccount Default,Default,0.00,862.93,-862.93,0.00,0.00,0.00,0.0000,Revalues for USD income statement accounts
48134,Revalues DEC-16 29-DEC-2016 2721715,Revalues for USD income statement accounts,NaN,NaN,2328,NaN,Revaluation,Revalue Profit/Loss,NaN,2211,...,SubAccount Default,Default,3517.20,0.00,3517.20,0.00,0.00,0.00,0.0000,Revalues for USD income statement accounts
48135,Revalues DEC-16 29-DEC-2016 2721715,Revalues for CHF income statement accounts,NaN,NaN,2328,NaN,Revaluation,Revalue Profit/Loss,NaN,2166,...,SubAccount Default,Default,19.73,0.00,19.73,0.00,0.00,0.00,0.0000,Revalues for CHF income statement accounts
48136,Revalues DEC-16 29-DEC-2016 2721715,Revalues for GBP income statement accounts,NaN,NaN,2328,NaN,Revaluation,Revalue Profit/Loss,NaN,2121,...,SubAccount Default,Default,271.57,0.00,271.57,0.00,0.00,0.00,0.0000,Revalues for GBP income statement accounts
48137,Revalues DEC-16 29-DEC-2016 2721715,Revalues for GBP income statement accounts,NaN,NaN,2328,NaN,Revaluation,Revalue Profit/Loss,NaN,3561,...,SubAccount Default,Default,173.52,0.00,173.52,0.00,0.00,0.00,0.0000,Revalues for GBP income statement accounts
48138,AT LOCAL: MMC PAYROLL A 2687064 16380624 2684630,DEC-16 MMC Pass Through EUR,NaN,NaN,2328,NaN,MMC PAYROLL,MMC Pass Through,NaN,4,...,SubAccount Default,Default,5187.66,0.00,5187.66,5187.66,0.00,5187.66,5550.7962,DEC-16 MMC Pass Through EUR
48139,AT LOCAL: MMC PAYROLL A 2687064 16380624 2684630,DEC-16 MMC Pass Through EUR,NaN,NaN,2328,NaN,MMC PAYROLL,MMC Pass Through,NaN,1,...,SubAccount Default,Default,45350.16,0.00,45350.16,45350.16,0.00,45350.16,48524.6712,DEC-16 MMC Pass Through EUR
48140,Revalues DEC-16 29-DEC-2016 2721715,Revalues for USD income statement accounts,NaN,NaN,2328,NaN,Revaluation,Revalue Profit/Loss,NaN,3911,...,SubAccount Default,Default,5.12,0.00,5.12,0.00,0.00,0.00,0.0000,Revalues for USD income statement accounts
48141,Revalues DEC-16 29-DEC-2016 2721715,Revalues for USD income statement accounts,NaN,NaN,2328,NaN,Revaluation,Revalue Profit/Loss,NaN,3751,...,SubAccount Default,Default,6.18,0.00,6.18,0.00,0.00,0.00,0.0000,Revalues for USD income statement accounts
48142,Revalues DEC-16 29-DEC-2016 2721715,Revalues for USD income statement accounts,NaN,NaN,2328,NaN,Revaluation,Revalue Profit/Loss,NaN,3711,...,SubAccount Default,Default,2.07,0.00,2.07,0.00,0.00,0.00,0.0000,Revalues for USD income statement accounts
48143,AT LOCAL: MMC DIVA A 2683071 16245868 2678103,DEC-16 MMC Pass Through EUR,NaN,NaN,2328,NaN,MMC DIVA,MMC Pass Through,NaN,17,...,SubAccount Default,Default,0.00,29.73,-29.73,0.00,29.73,-29.73,-31.8111,DEC-16 MMC Pass Through EUR
48144,AT LOCAL: MMC DIVA A 2641263 15510959 2615017,DEC-16 MMC Pass Through EUR,NaN,NaN,2328,NaN,MMC DIVA,MMC Pass Through,NaN,15,...,SubAccount Default,Default,0.00,133.86,-133.86,0.00,133.86,-133.86,-143.2302,DEC-16 MMC Pass Through EUR
48145,AT LOCAL: MMC DIVA A 2679793 16204651 2675653,DEC-16 MMC Pass Through EUR,NaN,NaN,2328,NaN,MMC DIVA,MMC Pass Through,NaN,16,...,SubAccount Default,Default,36.58,0.00,36.58,36.58,0.00,36.58,39.1406,DEC-16 MMC Pass Through EUR
48146,AT LOCAL: MMC DIVA A 2693924 16497598 2695540,DEC-16 MMC Pass Through EUR,NaN,NaN,2328,NaN,MMC DIVA,MMC Pass Through,NaN,25,...,SubAccount Default,Default,16.98,0.00,16.98,16.98,0.00,16.98,18.1686,DEC-16 MMC Pass Through EUR
48147,AT LOCAL: MMC FAH WEBADI REV SVM A 2669932 159...,233337 MAR AT-T4-AAP-1116-TP-Austria Global Al...,NaN,NaN,2328,NaN,MMC FAH WEBADI REV SVM,FAH Accrual,NaN,8,...,SubAccount Default,Default,0.00,436.36,-436.36,0.00,388.21,-388.21,-593.9613,Austria Global Allocation- Nov-16 GBP
48148,AT LOCAL: MMC FAH ADI A 2714559 16861121 2717051,253094-AT-T4-PB-1216-TP-GIT True Up-WNS USD,NaN,NaN,2328,NaN,MMC FAH ADI,Adjustment,NaN,13,...,SubAccount Default,Default,0.00,579.85,-579.85,0.00,606.00,-606.00,-606.0000,GIT True Up USD
48149,AT LOCAL: MMC FAH ADI A 2703006 16642680 2704500,250299 MAR AT-T4-AAP-1216-TP-Austria Global Al...,NaN,NaN,2328,NaN,MMC FAH ADI,Adjustment,NaN,93,...,SubAccount Default,Default,135.65,0.00,135.65,141.77,0.00,141.77,141.7700,Austria Global Allocation- Dec-16 USD
48150,AT LOCAL: MMC FAH ADI A 2703006 16642680 2704500,250299 MAR AT-T4-AAP-1216-TP-Austria Global Al...,NaN,NaN,2328,NaN,MMC FAH ADI,Adjustment,NaN,85,...,SubAccount Default,Default,54.88,0.00,54.88,57.36,0.00,57.36,57.3600,Austria Global Allocation- Dec-16 USD
48151,AT LOCAL: MMC FAH ADI A 2703006 16642680 2704500,250299 MAR AT-T4-AAP-1216-TP-Austria Global Al...,NaN,NaN,2328,NaN,MMC FAH ADI,Adjustment,NaN,77,...,SubAccount Default,Default,1750.09,0.00,1750.09,1829.02,0.00,1829.02,1829.0200,Austria Global Allocation- Dec-16 USD
48152,AT LOCAL: MMC FAH ADI A 2703006 16642680 2704500,250299 MAR AT-T4-AAP-1216-TP-Austria Global Al...,NaN,NaN,2328,NaN,MMC FAH ADI,Adjustment,NaN,25,...,SubAccount Default,Default,506.37,0.00,506.37,423.50,0.00,423.50,647.9550,Austria Global Allocation- Dec-16 GBP
48153,AT LOCAL: MMC FAH ADI A 2703006 16642680 2704500,250299 MAR AT-T4-AAP-1216-TP-Austria Global Al...,NaN,NaN,2328,NaN,MMC FAH ADI,Adjustment,NaN,19,...,SubAccount Default,Default,0.00,325.03,-325.03,0.00,325.03,-325.03,-347.7821,Austria Global Allocation- Dec-16 EUR

In [12]:
df.head()

,Batch Name,Journal Name,Unnamed: 2,Unnamed: 3,LEDGER_ID,Transaction Number,JE Source Name,JE Category Name,Vendor Name,Line Number,...,SubAcct Description,Interco Description,Net Debit Local,Net Credit Local,Net Local,Net Debit Entered,Net Credit Entered,Net Entered,Net USD Budget,Journal Description
0,Revalues JAN-16 29-JAN-2016 622859,Revalues for USD income statement accounts,NaN,NaN,2328,NaN,Revaluation,Revalue Profit/Loss,NaN,2901,...,SubAccount Default,Default,1.62,0.00,1.62,0.0,0.00,0.00,0.0000,Revalues for USD income statement accounts
1,Revalues JAN-16 29-JAN-2016 622859,Revalues for USD income statement accounts,NaN,NaN,2328,NaN,Revaluation,Revalue Profit/Loss,NaN,1471,...,SubAccount Default,Default,0.67,0.00,0.67,0.0,0.00,0.00,0.0000,Revalues for USD income statement accounts
2,AT LOCAL: MMC DIVA A 511798 8170733 592431,JAN-16 MMC Pass Through EUR,NaN,NaN,2328,NaN,MMC DIVA,MMC Pass Through,NaN,3,...,SubAccount Default,Default,0.00,17.45,-17.45,0.0,17.45,-17.45,-18.6715,JAN-16 MMC Pass Through EUR
3,AT LOCAL: MMC DIVA A 511798 8170733 592431,JAN-16 MMC Pass Through EUR,NaN,NaN,2328,NaN,MMC DIVA,MMC Pass Through,NaN,3,...,SubAccount Default,Default,0.00,63.97,-63.97,0.0,63.97,-63.97,-68.4479,JAN-16 MMC Pass Through EUR
4,AT LOCAL: MMC DIVA A 511798 8170733 592431,JAN-16 MMC Pass Through EUR,NaN,NaN,2328,NaN,MMC DIVA,MMC Pass Through,NaN,3,...,SubAccount Default,Default,0.00,783.59,-783.59,0.0,783.59,-783.59,-838.4413,JAN-16 MMC Pass Through EUR